### ISSUE TITLE
Are the models pretrained on ImageNet21k available?

### ISSUE THREAD

**Issue by KazuhideMimura** [masora1030/CVPR2022-Pretrained-ViT-PyTorch#1]
Thank you for your great work.
I am a researcher working on image recognition in the field of earth sciences, and I'm very interested in applying the proposed pretrained model to my project (detection and classification of microfossils).

I found the models pretrained on exfractal and RCDB datasets on [GoogleDrive](https://drive.google.com/drive/folders/1ikNUxJoMCx3Lx2TMrXfLdIwI6wwK5w_W?usp=sharing
) and I could somehow run finetune.py now.

I'm interested in comparing the performances on my dataset between models pretrained on fomula-driven shapes and general images. 
So, if possible, would you also share the model pretrained on ImageNet21k?

素晴らしいご研究ありがとうございます。
もし可能でしたら、ImageNet-21k でpretrain を行ったモデルも共有していただけないでしょうか。

**Comment by masora1030** [comment]
@KazuhideMimura 

Thank you for your interest in our research and for your model request.
We have now shared additional models of ViT-Tiny and Base pre-trained on ImageNet-21k respectively on [GoogleDrive](https://drive.google.com/drive/folders/1ikNUxJoMCx3Lx2TMrXfLdIwI6wwK5w_W?usp=sharing). (imagenet_21k_base.pth.tar, imagenet_21k_tiny.pth.tar)
We hope you will download each of them and use them for your own great research !

この度は、私たちの研究に興味を持っていただき誠にありがとうございます。
また、ImageNet-21kで事前学習済みのモデルパラメータのリクエストについて承りました。ただいま、ViT-Base/TinyをImageNet-21kで事前学習させたモデルチェックポイントを、それぞれ[GoogleDrive](https://drive.google.com/drive/folders/1ikNUxJoMCx3Lx2TMrXfLdIwI6wwK5w_W?usp=sharing)上にtarファイルとしてアップロードいたしましたので、ぜひご活用ください。
（数式ドリブンな画像の再帰的/幾何学的な画像特徴と微化石は、親和性があって非常に面白そうですね。。。！）
どうぞよろしくお願いいたします。

**Comment by KazuhideMimura** [comment]
Thank you for your quick response.

早速のご対応ありがとうございました．
微化石の分類は，論文が白黒印刷の時代に発展したということもあり，色情報よりも線の情報が重要視されます．
また，自然の生成物なのでフラクタル形状を学習することが特に有効なのではないかと考えました．
（論文でも，Flowers のデータセットで高い正解率を示していましたよね．偶然かもしれませんが…）

また何かありましたらご相談させてください．今後ともよろしくお願いいたします．
