### ISSUE TITLE
Clarify construction of ExFractalDB and ExFractalDB_render.sh

### ISSUE THREAD

**Issue by bbartoldson** [masora1030/CVPR2022-Pretrained-ViT-PyTorch#3]
Hi,

Could you please let me know if the script `ExFractalDB_render.sh` given [here](https://github.com/masora1030/CVPR2022-Pretrained-ViT-PyTorch/blob/main/exfractaldb_render/) creates the MV-FractalDB or the ExFractalDB dataset, and (if it creates the former dataset) provide instructions for randomly changing the viewpoint? 

The [README.md](https://github.com/masora1030/CVPR2022-Pretrained-ViT-PyTorch/blob/main/exfractaldb_render/README.md) seems to have two conflicting statements: 

1. "Run the bash script ExFractalDB_render.sh, you can get our Extended Fractal DataBase."  
2. "Note that this code is for constructing the MV-FractalDB, whereas you can construct the ExFractalDB by changing the view-point at random."

The `view_point` arg in the code [here](https://github.com/masora1030/CVPR2022-Pretrained-ViT-PyTorch/blob/main/exfractaldb_render/image_render/render.py) suggests that the script will create the MV-FractalDB dataset. It'd be great to know the code used to make the view point random.

Thank you very much!

Brian

**Comment by ryosuke-yamada** [comment]
Hi,
Thanks for your interest.
Additionally, thank you for your clarification of the conflicting statements.

> Could you please let me know if the script ExFractalDB_render.sh given [here](https://github.com/masora1030/CVPR2022-Pretrained-ViT-PyTorch/blob/main/exfractaldb_render/) creates the MV-FractalDB or the ExFractalDB dataset, and (if it creates the former dataset) provide instructions for randomly changing the viewpoint?

ExFractalDB_render.sh creates the MV-FractalDB.

To change random view-points, lines 166-168 of [this code](https://github.com/masora1030/CVPR2022-Pretrained-ViT-PyTorch/blob/main/exfractaldb_render/image_render/render.py) should be fixed as follows;
```
rotateX = random.uniform(-math.pi, math.pi)
rotateY = random.uniform(-math.pi, math.pi)
rotateZ = random.uniform(-math.pi, math.pi)
mat_rot=glm.rotate(mat_rot, rotateZ, glm.vec3(0.0, 0.0, 1.0))
mat_rot=glm.rotate(mat_rot, rotateY, glm.vec3(0.0, 1.0, 0.0))
mat_rot=glm.rotate(mat_rot, rotateX, glm.vec3(1.0, 0.0, 0.0))
```

And you do comment out line 164.

**Comment by bbartoldson** [comment]
That makes sense. Thank you!
